### ISSUE TITLE
It will be great if you could provide an example notebook to show how to use this tool.

### ISSUE THREAD

**Issue by xuzhang5788** [reymond-group/RAscore#1]
Thank you so much for your repo. Could you please explain how to use this tool combined with AiZynthfinder. It will be great if there is a case study.

**Comment by A-Thakkar** [comment]
A notebook has now been added to demonstrate usage of the RAscore. Can you elaborate on what you would like explained with regards to AiZynthfinder? Usage of the score is independent of AiZynthfinder.
