### ISSUE TITLE
Installation instructions are obsolete

### ISSUE THREAD

**Issue by rsanchezgarc** [reymond-group/RAscore#11]
Hi,

I tried to install your package using your instructions. but some packages incompatibilities arise in doing so.
I have managed to install it after trying a few versions. 

I am attaching a yml file ([RAscore_env.zip](https://github.com/reymond-group/RAscore/files/6894525/RAscore_env.zip))  so that you can install all dependencies with anaconda.

```
conda env create -f RAscore_env.yml
conda activate az_RAScore
pip  install --no-deps git+https://github.com/reymond-group/RAscore.git@master

```

Best wishes,

Ruben

**Comment by A-Thakkar** [comment]
Hi Rubem,

Thanks for pointing this out, i have had others mention it to me recently due to errors arising with XGBoost.

I have now added the specific versions to the setup.cfg so they should be installed properly now.

Thanks again and sorry for the inconvenience this caused you.

Amol
