### ISSUE TITLE
Keras load_model function failing

### ISSUE THREAD

**Issue by cthoyt** [reymond-group/RAscore#3]
The code from the example in the README fails due to a problem with the data in the models folder.

```python
....
nn_scorer = RAscore_NN.RAScorerNN('<path-to-repo>/RAscore/RAscore/model/models/DNN_chembl_fcfp_counts/model.h5')
```

A minimal code example to reproduce:

```python
from tensorflow import keras
keras.models.load_model('/Users/cthoyt/dev/RAScore/RAscore/model/models/DNN_chembl_fcfp_counts/model.h5')
Traceback (most recent call last):
  File "/Users/cthoyt/dev/RAscore/RAscore/model/__init__.py", line 26, in <module>
    _main()
  File "/Users/cthoyt/dev/RAscore/RAscore/model/__init__.py", line 21, in _main
    t = load_dnn_chembl()
  File "/Users/cthoyt/dev/RAscore/RAscore/model/__init__.py", line 17, in load_dnn_chembl
    return keras.models.load_model(DNN_CHEMBL_FCFP_COUNTS_MODEL_PATH)
  File "/Users/cthoyt/.virtualenvs/RAscore38/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 211, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/Users/cthoyt/.virtualenvs/RAscore38/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: /Users/cthoyt/dev/RAscore/RAscore/model/DNN_chembl_fcfp_counts/model.h5/{saved_model.pbtxt|saved_model.pb}
```

I'm not familiar with Tensorflow - but it looks like it's hoping to find some files inside the h5 file that are missing.

**Comment by A-Thakkar** [comment]
Can you update on whether this problem still persists after the latest update. Note that the default mdoel is the XGBoost model using the command line so this will not throw a tensorflow error. The reason for using the XGBoost model is that it is faster.

**Comment by cthoyt** [comment]
@A-Thakkar you should be able to see on the latest GitHub actions build (https://github.com/reymond-group/RAscore/runs/2022645956?check_suite_focus=true) that the same error is popping up. Since it's pretty explicitly defined what the argument is during that build, I hope we can at least rule out the version of tensorflow and the h5py libraries being used

**Comment by A-Thakkar** [comment]
This seems to be a known existing issue https://github.com/tensorflow/tensorflow/issues/33474 

The problem is because for some reason the model is linked to the cpu or gpu version and the device used. I have not seen it before but a temporary fix appears to be loading from a .tf file which is now supplied and passes the tests. Can you check whether it works on your machine now?

The actions link for the tests:
https://github.com/reymond-group/RAscore/actions/runs/621564375
