### ISSUE TITLE
Why not unzip models.zip?

### ISSUE THREAD

**Issue by cthoyt** [reymond-group/RAscore#4]
Because you're distributing data that needs to be unzipped, usage of RAScore can not be directly automated. One solution I had considered would be to load the models directly out of the zip folder with:

```python
# RAscore/model/models/__init__.py

import os
from zipfile import ZipFile
from tensorflow import keras

HERE = os.path.abspath(os.path.dirname(__file__))
MODELS = os.path.join(HERE, 'models.zip')


def load_dnn_chembl():
    with ZipFile(MODELS) as zip_file:
        with zip_file.open('models/DNN_chembl_fcfp_counts/model.h5') as file:
            return keras.models.load_model(file)
```

This fails because keras refuses to load models from file-like objects - it only wants to have file paths.

I tried the following which unzips the model file in a temporary directory only during loading, but it fails because of #3.

```python
# RAscore/model/models/__init__.py

import os
import tempfile
from zipfile import ZipFile
from tensorflow import keras

HERE = os.path.abspath(os.path.dirname(__file__))
MODELS = os.path.join(HERE, 'models.zip')

def load_dnn_chembl():
    with ZipFile(MODELS) as zip_file, tempfile.TemporaryDirectory() as tmp:
        zip_file.extract('models/DNN_chembl_fcfp_counts/model.h5', tmp)
        return keras.models.load_model(tmp)
```

Other alternates:

1. The `models.zip` folder is currently under GitHub's limit for file size. Unzip it and distribute it with the package itself. Then you can use `install_package_data=True` in the `setup.py` so it gets installed together and you can use the same trick I did in these examples to create consistent file paths that could be the default models for the predictor classes. This solution might be problematic for a PyPI upload since they do have a limit on size, but I'm not sure what it is.
2. Host the models (unzipped) on a repository like FigShare or Zenodo, then use a tool like [`pystow`](https://github.com/cthoyt/pystow) to automatically cache them for users in a consistent location that can be considered as the "default". Most people will only use your default model, so while extensibility to loading any model is nice, it's making a higher bar for new users.

All of these solutions are moot while #3 persists, but after that's fixed I'd be happy to submit demonstrating solution 1. If you'd like a demonstration of solution 2, please upload these files to a record on Zenodo and I can give a demo of that too.

**Comment by A-Thakkar** [comment]
Unfortunately I am struggling to reproduce the error, however it could help if rather than specifying the paths, i do as you have suggested and load them by default. This could mitigate some issues. I am looking into it and would be happy if you could see if it helps overcome the model loading problem.

Is there an issue loading the XGB model aswell?

**Comment by A-Thakkar** [comment]
Default models are unzipped and loaded automatically in a similar way to the suggestion. The file paths no longer need to be specified for the default models and the usage is now documented in the readme, as well as a jupyter notebook.

**Comment by cthoyt** [comment]
Great, this is exactly the kind of solution I was hoping for
