### ISSUE TITLE
Include requirements in setup.py and not requirements.txt

### ISSUE THREAD

**Issue by cthoyt** [reymond-group/RAscore#5]
Requirements.txt is a tool for web apps - since this code is packaged, it makes more sense to include in an `install_requires` entry in the `setup.py`

Some of these seem to be optional requirements for the model training - there is also a keyword for optional arguments for setup.py, but I'd suggest switching to a declarative setup.cfg file instead since it's much cleaner

**Comment by A-Thakkar** [comment]
Latest push should enable simpler installation. Requirements.txt has been removed and dependencies placed in install requires as recommended, optional extras for retraining also included in setup.py.

setup.cfg file may be used at a later date, but i couldn't get it to work for this update

**Comment by cthoyt** [comment]
If you want, I could send a PR to switch your setup.py to a setup.cfg

**Comment by A-Thakkar** [comment]
Sure, that would be great, and this time i will merge the contribution. Sorry for the last time.
